apiVersion: v1
kind: Namespace
metadata:
  name: cafe-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee
  namespace: cafe-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coffee
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
      - name: coffee
        image: suwatch01/coffeewebapp:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea
  namespace: cafe-apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tea 
  template:
    metadata:
      labels:
        app: tea 
    spec:
      containers:
      - name: tea 
        image: suwatch01/teawebapp:latest
        ports:
        - containerPort: 80